Task3.2
atilttt/GasparyanArtem-TKI-142-2024-2025 pull request #19
Opened 2024-10-13 17:07 UTC by ArtemGGA

#18

2024-10-14 16:51 UTC, MarinaPaley requested changes
Через рекуррентное выражение

2024-10-21 13:42 UTC, MarinaPaley requested changes

2024-10-21 13:42 UTC, MarinaPaley commented on 3.2.c
> +double next_term(double previous_term, int k);
const

2024-10-21 13:42 UTC, MarinaPaley commented on 3.2.c
> +int Int_input(void)
`int int_input(void)`
![cases](https://user-images.githubusercontent.com/26978698/213406039-603bfb33-7b86-4bf1-9564-3ec22e00c4f2.jpg)

2024-10-21 13:42 UTC, MarinaPaley commented on 3.2.c
> +    if (result != 1 || result < 0) {
проверка в отдельной функции

2024-10-21 13:42 UTC, MarinaPaley commented on 3.2.c
> +        if (k > 1) {
Это зачем?

2024-10-21 13:42 UTC, MarinaPaley commented on 3.2.c
> +    for (int k = 1; k <= n; ++k) {
k < n

2024-10-21 13:42 UTC, MarinaPaley commented on 3.2.c
> +double get_sum_dependet_e(const int n, const double e) {
В этой функции n вообще не используется

2024-10-21 14:26 UTC, MarinaPaley requested changes

2024-10-21 14:26 UTC, MarinaPaley commented on 3.2.c
> +int Integer_input(void);
Стили программирования
[CamelCase](https://ru.wikipedia.org/wiki/CamelCase)
[snake_case](https://ru.wikipedia.org/wiki/Snake_case)

2024-10-21 14:26 UTC, MarinaPaley commented on 3.2.c
> +/**
между функциями оставляйте, пожалуйста, одну строку.

2024-10-21 14:26 UTC, MarinaPaley commented on 3.2.c
> +double next_term(const double previous_term, int k);
а `k`в функции изменяется?

2024-10-21 14:26 UTC, MarinaPaley commented on 3.2.c
> +    check_n(n);
Объедините в один шаг

2024-10-21 14:26 UTC, MarinaPaley commented on 3.2.c
> +    const double e = input();
Проверка `epsilon > 0 ` более важна, а Вы ее не делаете. В случает с циклом до `n`, просто не пойдете, а в случае отрицательной погрешности - зациклитесь.

2024-10-28 10:57 UTC, MarinaPaley requested changes
не исправлено

2024-10-28 11:59 UTC, MarinaPaley requested changes
не исправили

2024-11-06 11:31 UTC, MarinaPaley requested changes

2024-11-06 11:31 UTC, MarinaPaley commented on 3.2.c
> +    pozitiv_double(e); // проверка epslion обьеденненная в один шаг //
Хочется спросить... и что? дважды вводите значение. второй раз проверяете. Но значение уходит никуда. Зачем?

2024-11-06 11:31 UTC, MarinaPaley commented on 3.2.c
> +    double term = 1.0;  // Начальный член a_1 = 1^4 / 1!
не учли в сумме первое слагаемое

2024-11-06 11:31 UTC, MarinaPaley commented on 3.2.c
> +        term = next_term(term, k);
поменять местами

2024-11-18 14:40 UTC, BalakinaEP requested changes

2024-11-18 14:40 UTC, BalakinaEP commented on 3.2.c
> +double get_sum_dependet_e(const int n, const double e);
double get_sum_dependet_e(const double e);

2024-11-18 14:40 UTC, BalakinaEP commented on 3.2.c
> +    if (parameter < DBL_EPSILON)
if (parameter <= DBL_EPSILON)

2024-11-18 14:40 UTC, BalakinaEP commented on 3.2.c
> +    return previous_term * (pow(k, 4) / k);
-1

2024-11-18 14:40 UTC, BalakinaEP commented on 3.2.c
> +    double term = 1.0;  // Начальный член a_1 = 1^4 / 1!
double sum = term ;

2024-11-18 14:40 UTC, BalakinaEP commented on 3.2.c
> +    while (term >= e + DBL_EPSILON)
(fabs(term) >= e - DBL_EPSILON)

2024-11-18 14:40 UTC, BalakinaEP commented on 3.2.c
> +        sum += term;
```
sum += term;;
term = next_term(term, k);
k++;
```

2024-11-25 11:58 UTC, MarinaPaley requested changes

2024-11-25 11:58 UTC, MarinaPaley commented on 3.2.c
> +    return (previous_term * (pow(k, 4) / k)) - 1;
`-1 * ...`

2024-11-25 11:58 UTC, MarinaPaley commented on 3.2.c
> +        term = next_term(term, k);
`term *= next_term(k);`

2024-11-29 12:54 UTC, BalakinaEP approved these changes

2024-11-29 16:29 UTC, merged