Feature3.3
atilttt/GasparyanArtem-TKI-142-2024-2025 pull request #20
Opened 2024-10-20 15:00 UTC by ArtemGGA

2024-10-21 13:51 UTC, MarinaPaley requested changes

2024-10-21 13:51 UTC, MarinaPaley commented on 3(3).c
> +double get_function(double x);
const

2024-10-21 13:51 UTC, MarinaPaley commented on 3(3).c
> +double get_current(double x, int k);
const

2024-10-21 13:51 UTC, MarinaPaley commented on 3(3).c
> +    return (1.0 / 4.0) * log((1 + x) / (1 - x)) + (1.0 / 2.0) * atan(x);
не проверяете ООФ

2024-10-28 11:01 UTC, MarinaPaley requested changes

2024-10-28 11:01 UTC, MarinaPaley commented on 3(3).c
> +double get_current(const double x, int k);
const

2024-10-28 11:01 UTC, MarinaPaley commented on 3(3).c
> +        exit(EXIT_FAILURE);
Убрать

2024-10-28 11:01 UTC, MarinaPaley commented on 3(3).c
> +    if (x <= - 1 + DBL_EPSILON || x >= 1 - DBL_EPSILON)
В main

2024-10-28 12:07 UTC, MarinaPaley requested changes

2024-10-28 12:07 UTC, MarinaPaley commented on 3(3).c
> +        if (x <= -1 + DBL_EPSILON || x >= 1 - DBL_EPSILON) {
неверно определили ООФ

2024-11-06 11:33 UTC, MarinaPaley requested changes

2024-11-06 11:33 UTC, MarinaPaley commented on 3(3).c
> +        if (x >= -1 + DBL_EPSILON && x <= 1 - DBL_EPSILON)  { //изменение ООФ//
неверно определена ООФ

2024-11-11 12:06 UTC, MarinaPaley requested changes

2024-11-11 12:06 UTC, MarinaPaley commented on 3(3).c
> +        if (x > -1 + DBL_EPSILON && x < 1 - DBL_EPSILON)  { //изменение ООФ//
`(x > -1 - DBL_EPSILON && x < 1 + DBL_EPSILON) `

2024-11-11 12:06 UTC, MarinaPaley commented on 3(3).c
> +        current = get_current(x, k);
поменять местами

2024-11-18 14:44 UTC, BalakinaEP requested changes

2024-11-18 14:44 UTC, BalakinaEP commented on 3(3).c
> +    if (step < DBL_EPSILON)
if (step <= DBL_EPSILON)

2024-11-18 14:44 UTC, BalakinaEP commented on 3(3).c
> +    while (fabs(current) > eps)
while (fabs(current) >= eps)

2024-11-18 14:44 UTC, BalakinaEP commented on 3(3).c
> +    int k = 0;
`int k = 1;`

2024-11-25 12:00 UTC, MarinaPaley approved these changes

2024-11-26 18:04 UTC, merged