Feature4.1
atilttt/GasparyanArtem-TKI-142-2024-2025 pull request #22
Opened 2024-10-28 09:35 UTC by ArtemGGA

2024-10-29 17:14 UTC, BalakinaEP requested changes
Определитесь кто автор у этого кода: вы или Егор Скрипников?

2024-10-29 17:14 UTC, BalakinaEP commented on 4.c
> +    int n = getPosInt();
Используйте беззнаковый тип данных для размера массива size_t

2024-10-29 17:14 UTC, BalakinaEP commented on 4.c
> +int findAdjSum(int* arr, int n, int sum);
const

2024-10-29 17:14 UTC, BalakinaEP commented on 4.c
> +void printMult3Idx(int* arr, int n);
const

2024-10-29 17:14 UTC, BalakinaEP commented on 4.c
> +void invertLastK(int* arr, int n, int k);
const

2024-10-29 17:14 UTC, BalakinaEP commented on 4.c
> +void fillUser(int* arr, int n);
const

2024-10-29 17:14 UTC, BalakinaEP commented on 4.c
> +void fillRand(int* arr, int n);
const

2024-10-29 17:14 UTC, BalakinaEP commented on 4.c
> +void checkK(int k, int n);
const

2024-10-29 17:14 UTC, BalakinaEP commented on 4.c
> +    int* arr = (int*)malloc(n * sizeof(int));
не проверили, что память выделилась

2024-10-29 17:14 UTC, BalakinaEP commented on 4.c
> +    showMenu();
Эта функция ничего в себе не несет. Зачем она?

2024-10-29 17:14 UTC, BalakinaEP commented on 4.c
> +        case 1:
Константы в коде

2024-10-29 17:14 UTC, BalakinaEP commented on 4.c
> +        case 2:
Константы в коде

2024-10-29 17:14 UTC, BalakinaEP commented on 4.c
> +            for (int i = 0; i < n; i++) {
size_t для обхода массива

2024-10-29 17:14 UTC, BalakinaEP commented on 4.c
> +    printf("\n");
Это отдельная функция

2024-10-29 17:14 UTC, BalakinaEP commented on 4.c
> +    for (int i = 0; i < n; i++) {
size_t

2024-10-29 17:14 UTC, BalakinaEP commented on 4.c
> +    for (int i = 0; i < n; i++) {
size_t
Повторяющийся код

2024-10-29 17:14 UTC, BalakinaEP commented on 4.c
> +    printMult3Idx(arr, n);
портите исходный массив

2024-10-29 17:14 UTC, BalakinaEP commented on 4.c
> +    int res = scanf("%d", &val);
value, result

2024-10-29 17:14 UTC, BalakinaEP commented on 4.c
> +    int val = getInt();
value

2024-10-29 17:14 UTC, BalakinaEP commented on 4.c
> +    printf("2 - Ввод с клавиатуры\n");
Константы в коде

2024-10-29 17:14 UTC, BalakinaEP commented on 4.c
> +    for (int i = 0; i < n; i++) {
size_t

2024-10-29 17:14 UTC, BalakinaEP commented on 4.c
> +        arr[i] = (rand() % 201) - 100;
Диапазон заполнения пользователь задает с клавиатуры

2024-10-29 17:14 UTC, BalakinaEP commented on 4.c
> +    for (int i = 0; i < n; i++) {
size_t

2024-10-29 17:14 UTC, BalakinaEP commented on 4.c
> +    for (int i = n - k; i < n; i++) {
size_t

2024-10-29 17:14 UTC, BalakinaEP commented on 4.c
> +    for (int i = 0; i < n; i++) {
size_t

2024-10-29 17:14 UTC, BalakinaEP commented on 4.c
> +    for (int i = 0; i < n - 1; i++) {
size_t

2024-11-18 13:14 UTC, BalakinaEP requested changes

2024-11-18 13:14 UTC, BalakinaEP commented on 4.c
> +    const size_t n = pozitiv_input();
const size_t n = (size_t) pozitiv_input();

2024-11-18 13:14 UTC, BalakinaEP commented on 4.c
> +    }
В отдельную функцию

2024-11-18 13:14 UTC, BalakinaEP commented on 4.c
> +        array[index] = (rand() % n);
Диапазон задаем с клавиатуры

2024-11-18 13:14 UTC, BalakinaEP commented on 4.c
> +    for (size_t i = n - k; i < n; ++i) {
k-1

2024-11-18 13:14 UTC, BalakinaEP commented on 4.c
> +    for (size_t i = n - k; i < n; ++i) {
В копии массива

2024-11-18 14:55 UTC, BalakinaEP requested changes

2024-11-18 14:55 UTC, BalakinaEP commented on 4.c
> +    if (value < 0) {
if (value <= 0) {

2024-11-18 14:55 UTC, BalakinaEP commented on 4.c
> +    return (size_t)value;
return value;

2024-11-18 14:55 UTC, BalakinaEP commented on 4.c
> +    check_array(array);
Отдельная функция

2024-11-18 14:55 UTC, BalakinaEP commented on 4.c
> +            const int max = input();
Убрать в функцию random_filling

2024-11-18 14:55 UTC, BalakinaEP commented on 4.c
> +void check_elements_k(int *array, int k, const size_t n) {
int* check_elements_k(int *array, int k, const size_t n) {

2024-11-18 14:55 UTC, BalakinaEP commented on 4.c
> +    check_array(array_2);
одна функция

2024-11-18 14:55 UTC, BalakinaEP commented on 4.c
> +    for (size_t i = n - k - 1; i < n; ++i)
for (size_t i = n - (k - 1); i < n; ++i)

2024-11-18 14:55 UTC, BalakinaEP commented on 4.c
> +}
return array_2;

2024-11-18 14:55 UTC, BalakinaEP commented on 4.c
> +    check_elements_k(array, k, n);
```
int* array2 = check_elements_k(array, k, n);
 print_array(array2, n);
free(array2);

```

2024-11-18 14:55 UTC, BalakinaEP commented on 4.c
> +    check_array(array);
Убрать

2024-11-18 14:55 UTC, BalakinaEP commented on 4.c
> +        if ((array[i] + array[i++]) == number)
for (size_t i = 0; i < n-1; ++i)
{
     if ((array[i] + array[i+1]) == number)
}

2024-11-25 12:06 UTC, MarinaPaley approved these changes

2024-11-25 12:06 UTC, MarinaPaley commented on 4.c
> +    printf("0 - ручной ввод, 1 - случайное заполнение\n");
Не надо использовать _&laquo;магические константы&raquo;_ в коде. Это не только признак дурновкусия, но и источник большого числа потенциальных ошибок. Привожу некоторые источники, потребные для Вашего самообразования:
- [ru.wikipedia.org](https://ru.wikipedia.org/wiki/Магическое_число_(программирование))
- [refactoring.guru](https://refactoring.guru/ru/replace-magic-number-with-symbolic-constant)
- [pvs-studio.com](https://pvs-studio.com/ru/blog/posts/cpp/0023/)
- [habr.com](https://habr.com/ru/post/328244/)

2024-11-25 12:06 UTC, MarinaPaley commented on 4.c
> +    int value;
`int value = 0;`

2024-11-25 12:06 UTC, MarinaPaley commented on 4.c
> +    check_array(new_array);
`int* new_array = create_array(n);`

2024-11-26 18:20 UTC, merged