Feature4.2
atilttt/GasparyanArtem-TKI-142-2024-2025 pull request #23
Opened 2024-11-16 17:38 UTC by ArtemGasparyan

2024-11-25 12:13 UTC, MarinaPaley requested changes

2024-11-25 12:13 UTC, MarinaPaley commented on function_for_4.2.c
> +    }
Тогда в отдельную функцию

2024-11-25 12:13 UTC, MarinaPaley commented on function_for_4.2.c
> +            ++counter;
1. Считаете количество элементарных чисел. Размер массива - размер + количество. Новый массив этого размера
2. Сама эта функция

2024-12-02 12:44 UTC, BalakinaEP requested changes

2024-12-02 12:44 UTC, BalakinaEP commented on function_for_4.2.h
> +void print_replacement(int *array, const size_t n);
Убрать

2024-12-02 12:44 UTC, BalakinaEP commented on function_for_4.2.c
> +int* copy_array(const int *array, const size_t n) {
check_array(array);

2024-12-02 12:44 UTC, BalakinaEP commented on function_for_4.2.c
> +void random_filling(int *array, const size_t n) {
check_array(array);

2024-12-02 12:44 UTC, BalakinaEP commented on function_for_4.2.c
> +void user_input_filling(int *array, const size_t n) {
check_array(array);

2024-12-02 12:44 UTC, BalakinaEP commented on function_for_4.2.c
> +}
В main

2024-12-02 12:44 UTC, BalakinaEP commented on function_for_4.2.c
> +    free(new_array);
в main

2024-12-02 12:44 UTC, BalakinaEP commented on function_for_4.2.c
> +    int *A = create_array(n);
arr

2024-12-02 13:24 UTC, merged