Feature4.3
atilttt/GasparyanArtem-TKI-142-2024-2025 pull request #30
Opened 2024-12-06 18:02 UTC by atilttt

2024-12-09 11:11 UTC, BalakinaEP requested changes

2024-12-09 11:11 UTC, BalakinaEP commented on function_for_4.3.c
> +        array[i] = (int*)malloc(m * sizeof(int));
check_array(array[i]);

2024-12-09 11:11 UTC, BalakinaEP commented on function_for_4.3.c
> +    printf("Your array:\n");
check_array(array);

2024-12-09 11:11 UTC, BalakinaEP commented on function_for_4.3.c
> +    int **new_array = create_array(n, m);
check_array(array);

2024-12-09 11:11 UTC, BalakinaEP commented on function_for_4.3.c
> +    int **new_array = copy_array(array, n, m);
check_array(array);

2024-12-09 11:11 UTC, BalakinaEP commented on function_for_4.3.c
> +        for(size_t j = 1; j < m; j++)
j = 0;

2024-12-09 11:11 UTC, BalakinaEP commented on function_for_4.3.c
> +        }
Этот цикл выше

2024-12-09 11:11 UTC, BalakinaEP commented on function_for_4.3.c
> +        }
Вот сюда. до скобки внутрь цикла

2024-12-09 11:11 UTC, BalakinaEP commented on main.c
> +    print_array(new_array, n, m + counter(array, n, m));
new_array_2

2024-12-16 12:53 UTC, MarinaPaley approved these changes

2024-12-16 12:53 UTC, MarinaPaley commented on function_for_4.3.c
> +    check_array(array);
не нужно

2024-12-16 13:51 UTC, merged