документация и выполнение Задание 1.3
atilttt/GasparyanArtem-TKI-142-2024-2025 pull request #6
Opened 2024-09-20 11:44 UTC by ArtemGGA

#5

2024-09-23 13:14 UTC, MarinaPaley requested changes

2024-09-23 13:14 UTC, MarinaPaley commented on 1(3).c
> +    scanf("%lf", &U);
Уберите в отдельную функцию, как на лекции `Input`

2024-09-23 13:14 UTC, MarinaPaley commented on 1(3).c
> +    const int time = 1200.0;
`const double time`

2024-09-23 14:41 UTC, ArtemGGA commented
#6

2024-09-25 09:57 UTC, MarinaPaley requested changes

2024-09-25 09:57 UTC, MarinaPaley commented on 1(3).c
> + * return рассчитанное значение
`рассчитанное значение` чего?

2024-09-25 09:57 UTC, MarinaPaley commented on 1(3).c
> +    if (result != 2)
1. Не успела до конца прочитать это. Не надо проверять, так как Вы делаете это неправильно
2. Почему 2? Если просили ввести одно число, значит надо 1.
3. Вы в поток ошибок написали (зачем-то по-английски) сообщение. И? Если ошибка произошла, то необходимо выйти из приложения

2024-09-30 11:00 UTC, MarinaPaley approved these changes

2024-09-30 11:00 UTC, MarinaPaley commented on 1(3).c
> +double getA(const double time, double I, double U);
`double getA(const double time, const double I, const double U);`

2024-09-30 11:01 UTC, merged